Decorators
ScaleUp-Academy-ExcellenTeam22/decorators-Orshahar91 pull request #1
Opened 2022-04-30 19:58 UTC by Orshahar91

2022-05-24 07:16 UTC, mattisevitt requested changes

2022-05-24 07:16 UTC, mattisevitt commented on ex0.py
> +    :return: A decorator.
This documentation is enough, no need to document all the innner functions.

2022-05-24 07:16 UTC, mattisevitt commented on ex0.py
> +def type_check(correct_type):
Use type hints and return types -docum
https://www.geeksforgeeks.org/duck-typing-in-python/
https://stackoverflow.com/questions/125367/dynamic-type-languages-versus-static-type-languages
https://docs.python.org/3/library/typing.html
https://realpython.com/lessons/pros-and-cons-type-hints/

2022-05-24 07:16 UTC, mattisevitt commented on ex0.py
> +    return num*2
This should not be here.
Don’t use git add -a ever, use git add -p
https://git-scm.com/docs/git-add

2022-05-24 07:16 UTC, mattisevitt commented on ex1.py
> +def surprise(function):
Use type hints and return types -docum
https://www.geeksforgeeks.org/duck-typing-in-python/
https://stackoverflow.com/questions/125367/dynamic-type-languages-versus-static-type-languages
https://docs.python.org/3/library/typing.html
https://realpython.com/lessons/pros-and-cons-type-hints/

2022-05-24 07:16 UTC, mattisevitt commented on ex1.py
> +    Decorator that print surprise instead of the original functionality.
*that prints

2022-05-24 07:16 UTC, mattisevitt commented on ex1.py
> +times(2)
File has no top level environment of the program
https://docs.python.org/3/library/__main__.html

2022-05-24 07:17 UTC, mattisevitt approved these changes

2022-05-26 15:37 UTC, talbarfm approved these changes

2022-06-15 17:55 UTC, merged